version: "3.8"
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  scraper:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    links:
      - database
    environment:
      HOST: database
    ports:
      - "8080:80"
